### ISSUE TITLE
Has No Field Emit Signal Compile Error

### ISSUE THREAD

**Issue by bendangelo** [HaxeGodot/squash-the-creeps-3d#1]
Trying to compile your game using `haxe build.hxml` and get this error:

```
scripts/Player.hx:72: characters 9-19 : godot.CustomSignal<() -> Void> has no field emitSignal
scripts/Mob.hx:28: characters 14-24 : godot.CustomSignal<() -> Void> has no field emitSignal
```

Using Godot 3.3.0, haxe 4.2.2.

**Comment by ibilon** [comment]
Which version of the externs are you using? It requires the 3.3.0 version.

**Comment by bendangelo** [comment]
I believe I'm using 3.3.0.

```
haxelib install godot 3.3.0                                                                                                                        
You already have godot version 3.3.0 installed
You already have hxcs version 4.2.0 installed
```

I'm assuming this works fine on your end?

**Comment by ibilon** [comment]
Actually I was the one testing with the wrong version, the main branch shouldn't have had the custom signal commit yet, try using the project at commit https://github.com/HaxeGodot/squash-the-creeps-3d/tree/d2ca29118c9e39bf831f02cae658ba6e4f6cc4fa (redownloading it or `git checkout d2ca29118c9e39bf831f02cae658ba6e4f6cc4fa`).

**Comment by bendangelo** [comment]
ok thanks.
