### ISSUE TITLE
File "libs/ilib/peReader.ml", line 80, characters 8-14: Assertion failed

### ISSUE THREAD

**Issue by rayanmargham** [HaxeGodot/squash-the-creeps-3d#2]
When Attempting to build haxe you'll get this error.

**Comment by ibilon** [comment]
Which haxe version do you have?

**Comment by rayanmargham** [comment]
4.1.5

**Comment by ibilon** [comment]
I think this pull request https://github.com/HaxeFoundation/haxe/pull/9996 is required, so that means at least haxe 4.2.
